postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  dbname: ${POSTGRES_DBNAME}
httpServer:
  port: 8080
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
redis:
  addr: ${REDIS_ADDR}
  password: ${REDIS_PASSWORD}