postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  dbname: ${POSTGRES_DBNAME}
httpServer:
  port: 8080
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  webhookUrl: ${TELEGRAM_WEBHOOK_URL}
redis:
  addrs: ${REDIS_ADDRS}
  password: ${REDIS_PASSWORD}